// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nfawysfgumesbopeixzm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5mYXd5c2ZndW1lc2JvcGVpeHptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMzY4NzIsImV4cCI6MjA3MzYxMjg3Mn0.u1VGMgQ1NlBZTPSR3RaIhBPXvsrzg35whAeem2V9Y6M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});